### ISSUE TITLE
Any chance for a new release on pypi?

### ISSUE THREAD

**Issue by foosel** [mrjoes/sockjs-tornado#115]
The latest release on pypi is 1.0.3 from April 2016, however this repository has seen a couple of fixes since then (#83, #104, #106) and also has at least one pending PR that is crucial for continued compatibility with recent Tornado releases (#114 to solve #113).

Any chances to get #114 merged and push out a new release (1.0.4?) to pypi? The number of monkey patches needed to keep this usable in OctoPrint are starting to get a bit overwhelming and installing from a rolling Github repo is not really the best approach for production either. 

Is there anything that I could do to help make this happen?

**Comment by timabbott** [comment]
The Zulip project would also very much appreciate a release.

**Comment by mrjoes** [comment]
Done.
