### ISSUE TITLE
Reflected-XSS Vulnerability

### ISSUE THREAD

**Issue by florinnania** [mrjoes/sockjs-tornado#119]
An RXSS vulnerability has been observed using the README example.

To reproduce, run the following simplified echo SockJS server application:

```
from tornado import web, ioloop
from sockjs.tornado import SockJSRouter, SockJSConnection

class EchoConnection(SockJSConnection):
    def on_message(self, msg):
        self.send(msg)

if __name__ == '__main__':
    EchoRouter = SockJSRouter(EchoConnection, '/echo')

    app = web.Application(EchoRouter.urls)
    app.listen(9999)
    ioloop.IOLoop.instance().start()
```

Then, visit this url: http://localhost:9999/echo/201/nurtnfen/htmlfile?c=alert(1) 

I believe this is cause by not checking the non-alphanumeric symbols in [htmlfile.py](https://github.com/mrjoes/sockjs-tornado/blob/master/sockjs/tornado/transports/htmlfile.py)

**Comment by mrjoes** [comment]
Thanks, fixed and deployed a new release.
