### ISSUE TITLE
How to set request.argument ?

### ISSUE THREAD

**Issue by omgbbqhaxx** [mrjoes/sockjs-tornado#56]
The First: https://sockjs-tornado.readthedocs.org/en/latest/mod_session.html#sockjs.tornado.session.ConnectionInfo

The Second: https://github.com/mrjoes/sockjs-tornado/blob/master/sockjs/tornado/conn.py#L28-L31

But I don't know how pass some data to request.argument...

And I just tried... But failed.

```
conn = new SockJS('http://chatsocial.me/chat?argu=some');
```

What should I do?

**Comment by opyate** [comment]
Just checking if this is related: If I set the ```prefix``` to ```r"/ws/(.*)/?"```, is the extracted path component available in ```info``` in ```on_open```? Or can I write ```on_open``` as ```on_open(self, info, path)```?
