### ISSUE TITLE
Expose origin header to ConnectionInfo object

### ISSUE THREAD

**Issue by normanjaeckel** [mrjoes/sockjs-tornado#62]
There were added some headers to the info object in #20. The docstrings says something about the origin header, but the header is not included in the _exposed_headers list. But I would like to get it later in my on_open method. (Or can you tell me another smart way to check on which URL the client was when he established the connection?) Thank you very much.

**Comment by Hiestaa** [comment]
+1, for my specific use-case I would require to have the 'Host' header exposed.

A question though: why not exposing all headers, or allow the exposed headers to be configurable somehow? I don't see how hard-coding what you consider to be "useful" headers can be good.

**Comment by Hiestaa** [comment]
@normanjaeckel The white list of headers has been removed, all the headers are now exposed. I think you can close the issue.

**Comment by normanjaeckel** [comment]
Thanks.
