### ISSUE TITLE
Stats reporting does not decrement on .close() call

### ISSUE THREAD

**Issue by coulix** [mrjoes/sockjs-tornado#78]
Start server as described in the gist:

https://gist.github.com/coulix/8179de3a36d7e208b0c2

Open `demo.html` 
Navigate to localhost:8888/stats/ 
Refresh `demo.html` 3 times.

    {"conn_active":3,"conn_ps":  {"accumulator":0,"last_average":0.0,"period":10,"stream":{"maxlen":null},"sum":0},"pack_recv_ps":{"accumulator":0,"last_average":0.0,"period":10,"stream":{"maxlen":null},"sum":0},"pack_sent_ps":{"accumulator":0,"last_average":0.0,"period":10,"stream":{"maxlen":null},"sum":0},"sess_active":0,"sess_transports":{"websocket":0}}

You will see "conn_active":3. I guess that is an error no?

**Comment by coulix** [comment]
The session is closed an properly decremented but why is the connection not decremented when the page is reloaded?

**Comment by mrjoes** [comment]
Probably better late than never. For polling transports session will have to timeout, for websockets - it is up for OS to notify that connection was closed.
