### ISSUE TITLE
Use as a Client to an external SockJS server

### ISSUE THREAD

**Issue by charyorde** [mrjoes/sockjs-tornado#79]
Can SockJS-tornado be used as a client on the server-side?

I have an external SockJS and I want to connect to it as client from the server-side.

**Comment by FZambia** [comment]
SockJS-tornado is server itself so it can not be used as SockJS client.

External SockJS server probably supports raw websocket endpoint - you can connect to it using any rfc 6455 compliant websocket library

**Comment by charyorde** [comment]
Thanks
