### ISSUE TITLE
 New release of sockjs-tornado

### ISSUE THREAD

**Issue by ChrisJamesC** [mrjoes/sockjs-tornado#88]
I noticed that the latest - and only - release of sockjs-tornado is v1.0.0 and it's from more than 2 years ago (April 3rd, 2013). 

In the mean time there seems to have been lots of commits and pull requests merged. 

I looked for information online but could not understand why no new release has been cut. Is there another place I should look at for stable releases of Tornado or should I just use the latest code on Master?

**Comment by mrjoes** [comment]
I'll release new build later today.

**Comment by ChrisJamesC** [comment]
Thanks for your response!

**Comment by didiersmith** [comment]
Do you mind rolling another release? We'd love to use the permessage-deflate stuff added in https://github.com/mrjoes/sockjs-tornado/commit/4d5e88b3c907bed05b52087f40cdd3dc947e9679 but our build system prefers to pull versioned dependencies from pip instead of building them from github. Thanks!

**Comment by mrjoes** [comment]
And this was completed.
